# Generated by Django 5.0 on 2026-06-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_dicebear_avatar_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('qa', 'Quality Assurance')], max_length=20),
        ),
    ]
