# Generated by Django 5.0 on 2026-05-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callanalysis',
            name='top_issues',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
