# Generated by Django 5.0 on 2026-04-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='callanalysis',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
