name: call_center_manager_dashboard
description: Call Center Manager Dashboard - Flutter mobile app for monitoring and reports
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
 
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  flutter_secure_storage: ^10.3.1
  fl_chart: ^0.66.2
  shimmer: ^3.0.0
  intl: ^0.20.0
  http: ^1.6.0
  shared_preferences: ^2.5.5
  firebase_core: ^4.10.0
  firebase_messaging: ^16.3.0
  flutter_local_notifications: ^21.0.0
  flutter_staggered_animations: ^1.1.1
  lottie: ^3.1.0
  google_fonts: ^6.2.1
  badges: ^3.1.2
  auto_size_text: ^3.0.0
  audioplayers: ^6.1.0
  path_provider: ^2.1.6
  open_filex: ^4.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2




flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/vocalys_logo.png

