from django.db import models
from django.contrib.auth.models import User


class Report(models.Model):
    """
    Represents a periodic quality report generated by a QA user.
    The report content is initially drafted by the AI service,
    then reviewed and edited by QA before being published to the Manager.

    Lifecycle: draft → (QA reviews and edits) → published
    """

    PERIOD_CHOICES = [
        ('daily', 'Daily'),
        ('weekly', 'Weekly'),
    ]

    STATUS_CHOICES = [
        ('draft', 'Draft'),         # Created by AI, pending QA review
        ('published', 'Published'), # Reviewed by QA and visible to Manager
    ]

    # The QA user who generated and owns this report
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    # Whether this is a daily or weekly report
    period = models.CharField(max_length=10, choices=PERIOD_CHOICES)

    # Current lifecycle status of the report
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    # The date range this report covers
    date_from = models.DateField()
    date_to = models.DateField()

    # AI-generated content, editable by QA before publishing
    summary = models.TextField(blank=True, default='')          # Main problems + suggested solutions
    recommendations = models.TextField(blank=True, default='')  # General improvement recommendations
    positives = models.TextField(blank=True, default='')        # Positive highlights worth recognizing

    # Statistics computed at generation time and saved as JSON
    top_issues = models.JSONField(default=list)       # Top 5 recurring issues in the period
    sentiment_stats = models.JSONField(default=dict)  # Sentiment label distribution counts

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Return a readable string identifying the report by period and date range."""
        return f"{self.period} report ({self.date_from} → {self.date_to}) by {self.created_by}"